name: Baseline Kernel Build (No Mods)

name: Nom de votre Build

on:
  # push:          <-- Mettez un '#' devant "push" pour le désactiver
  #   branches: [ main ]
  workflow_dispatch: # <-- Cette ligne ajoute le bouton "Run workflow" manuel


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y bc bison build-essential curl flex g++-aarch64-linux-gnu gcc-aarch64-linux-gnu git libssl-dev clang lld llvm zip

      - name: Clone Sources
        run: |
          git clone https://github.com/LineageOS/android_kernel_motorola_sm8250 --depth=1 -b lineage-23.2 source

      
      - name: Compile Baseline
        run: |
          # D'abord, on se déplace dans le dossier contenant le code
          cd source
          
          # Maintenant, on peut vérifier le contenu
          echo "Contenu actuel du répertoire source :"
          ls -R arch/arm64/configs/
          
          # Diagnostic pour trouver le fichier
          find . -name "*kiev*defconfig"
