name: Build Kernel ReSukiSU

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARCH: arm64
      CROSS_COMPILE: aarch64-linux-gnu-
      CC: clang
      CLANG_TRIPLE: aarch64-linux-gnu-
      LD: ld.lld
      LLVM: 1
      LLVM_IAS: 1

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          path: source
          fetch-depth: 0

      - name: Setup Environment
        run: |
          sudo apt-get update && sudo apt-get install -y clang lld llvm
          mkdir -p source/out

      - name: Integrate ReSukiSU
        run: |
          cd source
          git clone https://github.com/ReSukiSU/ReSukiSU KernelSU
          sed -i '1i obj-y += KernelSU/' Makefile
          
          # Patch du scheduler
          CORE_C=$(find kernel -name "core.c" | head -n 1)
          sed -i '/#include <linux\/sched\/rt.h>/a #include "../KernelSU/kernel/ksu.h"' "$CORE_C"
          sed -i '/context_switch(rq, prev, next);/i \    ksu_handle_trace_sched_switch(prev, next);' "$CORE_C"

      - name: Configure Kernel
        run: |
          cd source
          # Application de la config
          make O=out ARCH=arm64 vendor/lito-perf_defconfig
          
          # Activation KSU et désactivation LTO
          echo "CONFIG_KSU=y" >> out/.config
          sed -i 's/CONFIG_LTO_CLANG=y/# CONFIG_LTO_CLANG is not set/' out/.config
          echo "CONFIG_LTO_NONE=y" >> out/.config
          
          # Finalisation config
          make O=out ARCH=arm64 olddefconfig

      - name: Compile Kernel
        run: |
          cd source
          make O=out ARCH=arm64 -j$(nproc) Image
