name: Build Kernel with KSU and SUSFS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y bc bison build-essential curl flex g++-aarch64-linux-gnu gcc-aarch64-linux-gnu git libssl-dev clang lld llvm zip

      - name: Clone Sources
        run: |
          git clone https://github.com/LineageOS/android_kernel_motorola_sm8250 --depth=1 -b lineage-23.2 source
          git clone https://github.com/ReSukiSU/ReSukiSU KSU
          git clone https://gitlab.com/simonpunk/susfs4ksu susfs

      - name: Patch Kernel
        run: |
          cd source
          # Intégration KSU
          cp -r $GITHUB_WORKSPACE/KSU/kernel drivers/kernelsu
          # Supprimer le fichier .git pour éviter l'erreur de sous-module
          rm -rf drivers/kernelsu/.git
          
          # Intégration SUSFS
          cp -r $GITHUB_WORKSPACE/susfs/* .
          
          # Patchs nécessaires
          echo "obj-\$(CONFIG_KSU) += kernelsu/" >> drivers/Makefile
          sed -i "/endmenu/i\source \"drivers/kernelsu/Kconfig\"" drivers/Kconfig

      - name: Compile Kernel
        run: |
          cd source
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CC=clang
          export CLANG_TRIPLE=aarch64-linux-gnu-
          
          mkdir -p out
          
          # Configuration standard
          make O=out ARCH=arm64 vendor/lito-perf_defconfig
          
          # Activation forcée des options KSU et SUSFS dans le .config
          cat >> out/.config <<EOF
          CONFIG_KSU=y
          CONFIG_KSU_SUSFS=y
          CONFIG_KSU_SUSFS_SUS_PATH=y
          CONFIG_KSU_SUSFS_SUS_MOUNT=y
          CONFIG_KSU_SUSFS_SUS_KSTAT=y
          CONFIG_KSU_SUSFS_SPOOF_UNAME=y
          CONFIG_KSU_SUSFS_ENABLE_LOG=y
          CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y
          CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y
          EOF
          
          # Finalisation de la configuration
          make O=out ARCH=arm64 olddefconfig
          
          # Compilation
          make O=out ARCH=arm64 -j$(nproc)
