name: Build ReSukiSU Kernel

on:
  push:
    branches: [ lineage-23.2 ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          repository: 'LineageOS/android_kernel_motorola_sm8250'
          ref: 'lineage-23.2'
          submodules: 'recursive'

      - name: Inject and Setup ReSukiSU
        run: |
          # Création du script d'intégration à la volée
          cat << 'EOF' > setup_resukisu.sh
          #!/bin/sh
          set -eu
          GKI_ROOT=$(pwd)
          if test -d "$GKI_ROOT/common/drivers"; then DRIVER_DIR="$GKI_ROOT/common/drivers"; else DRIVER_DIR="$GKI_ROOT/drivers"; fi
          DRIVER_MAKEFILE=$DRIVER_DIR/Makefile
          DRIVER_KCONFIG=$DRIVER_DIR/Kconfig
          echo "[+] Setting up ReSukiSU..."
          git clone https://github.com/ReSukiSU/ReSukiSU KernelSU
          cd "$DRIVER_DIR"
          ln -sf "$(realpath --relative-to="$DRIVER_DIR" "$GKI_ROOT/KernelSU/kernel")" "kernelsu"
          grep -q "kernelsu" "$DRIVER_MAKEFILE" || printf "\nobj-\$(CONFIG_KSU) += kernelsu/\n" >> "$DRIVER_MAKEFILE"
          grep -q "source \"drivers/kernelsu/Kconfig\"" "$DRIVER_KCONFIG" || sed -i "/endmenu/i\source \"drivers/kernelsu/Kconfig\"" "$DRIVER_KCONFIG"
          EOF
          
          # Exécution du script
          chmod +x setup_resukisu.sh
          ./setup_resukisu.sh

      - name: Build Kernel
        run: |
          make clean && make mrproper
          make ARCH=arm64 vendor/kona-perf_defconfig
          
          export PATH=/opt/proton-clang/bin:$PATH
          make -j$(nproc) ARCH=arm64 \
            CC=clang LD=ld.lld LLVM=1 LLVM_IAS=1 \
            CROSS_COMPILE=aarch64-linux-gnu- \
            HOSTCC=gcc HOSTCXX=g++ \
            CONFIG_KSU=y

      - name: Upload Kernel Image
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-Image-Kiev
          path: out/arch/arm64/boot/Image.gz-dtb
          if-no-files-found: warn
